import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home = ()=>  (
    <div className={styles.container}>
      <Head>
        <title>Flesh Cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Flesh Cards
        </h1>

        <p className={styles.description}>
          your smart flash cards app
        </p>
        <div className={styles.grid}>
          <div className={styles.button}>
            <Link href="/cards/new-deck">Get Started!</Link>
          </div>
          <div className={styles.button}>
            <Link href="/cards/desks">Checkout Decks!</Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        hehe
      </footer>
    </div>
  );

export default Home; 